upd workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,12 +34,14 @@ jobs:
 
       - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
-        run: |
+        run: |+
           git pull --rebase --autostash
 
           nix run .#updateLocks
 
-          git commit -a -m "action: Update flake locks" && git push
+          git commit -a -m "action: Update flake locks" \
+                                 && git push || echo "push failed!"
+
       - env:
           CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
           CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
