upd ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,6 +1,9 @@
 jobs:
   nixCI:
     name: Nix CI
+    permissions:
+      actions: write
+      contents: write
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout this repo
@@ -14,7 +17,7 @@ jobs:
             trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
             keep-outputs = true
       - name: Restore and cache Nix store
-        uses: deemp/cache-nix-too@v1
+        uses: nix-community/cache-nix-action@v1
         with:
           key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
           linux-gc-enabled: true
@@ -22,7 +25,6 @@ jobs:
           macos-gc-enabled: true
           macos-max-store-size: 15000000000
           restore-keys: |
-            nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
             nix-${{ matrix.os }}-cachix-
       - name: Remove old cache profiles
         run: rm -rf /nix/var/nix/profiles/cache
@@ -32,6 +34,11 @@ jobs:
           git config --global user.name github-actions
           git config --global user.email github-actions@github.com
       - if: matrix.os == 'ubuntu-22.04'
+        name: Format Nix files
+        run: |-
+          nix profile install .#format
+          nix run .#format
+      - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
         run: |-
           git pull --rebase --autostash
@@ -39,8 +46,11 @@ jobs:
           nix profile install .#updateLocks
           nix run .#updateLocks
 
-          git commit -a -m "action: Update flake locks" \
-                                 && git push || echo "push failed!"
+          git add .
+          git commit \
+            -m "action: Update flake locks" \
+            || echo "commit failed!"
+          git push
       - if: matrix.os == 'ubuntu-22.04'
         name: Build docs
         run: |
@@ -59,13 +69,17 @@ jobs:
           force_orphan: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs/dist
-      - env:
-          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
-          CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
-        name: Push flakes to Cachix
+      - name: Save flakes
         run: |-
-          nix profile install .#pushToCachix
-          nix run .#pushToCachix
+          nix profile install .#saveFlakes
+          nix run .#saveFlakes
+      - name: Purge cache
+        uses: deemp/purge-cache@v1
+        with:
+          accessed: false
+          created: true
+          debug: true
+          max-age: 172800
     strategy:
       matrix:
         os:
