upd workflows

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -34,16 +34,16 @@ jobs:
       - if: matrix.os == 'ubuntu-22.04'
         name: Format Nix files
         run: |+
-          nix run .#format
           nix profile install .#format
+          nix run .#format
 
       - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
         run: |+
           git pull --rebase --autostash
 
-          nix run .#updateLocks
           nix profile install .#updateLocks
+          nix run .#updateLocks
 
           git commit -a -m "action: Update flake locks" \
                                  && git push || echo "push failed!"
@@ -53,8 +53,8 @@ jobs:
           CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
         name: Push flakes to Cachix
         run: |+
-          nix run .#pushToCachix
           nix profile install .#pushToCachix
+          nix run .#pushToCachix
 
     strategy:
       matrix:
@@ -79,13 +79,17 @@ jobs:
             substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
             trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
             keep-outputs = true
-      - name: Build docs
+      - name: Build docs.
         run: |
-          nix run .#genDocs
           nix profile install .#genDocs
+          nix run .#genDocs
 
 
           cp -r docs/book docs/dist
+      - name: Update docs
+        run: |
+          git add "docs/src"
+          git commit -a -m "Update docs" && git push || echo "push failed!"
       - name: GitHub Pages action
         uses: peaceiris/actions-gh-pages@v3.9.3
         with:
